name: GraalVM Test Parallel
on:
  push:
    branches:
      - test-parallel-native
jobs:
  native_test_matrix_prep:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-native-test-matrix.outputs.matrix }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Set native test matrix"
        id: set-native-test-matrix
        run: |
          nativeTestTasks=$(./gradlew tasks --no-daemon --all | grep -w "nativeTest" | sed 's/\(.*\) - Executes the test native binary/\"\1\"/' | tr '\n' ',' | sed 's/.$//')
          echo "matrix={\"native_test_task\":[$(echo $nativeTestTasks)]}"
