name: GraalVM Test Parallel
on:
  push:
    branches:
      - test-parallel-native
jobs:
  native_test_matrix_prep:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
    outputs:
      matrix: ${{ steps.set-native-test-matrix.outputs.matrix }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup GraalVM CE"
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2
      - name: "Set native test matrix"
        id: set-native-test-matrix
        shell: bash
        run: |
          ./gradlew tasks --no-daemon --all | grep -w "nativeTest"
