name: GraalVM Test Parallel
on:
  push:
    branches:
      - test-parallel-native
jobs:
  native_test_matrix_prep:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-native-test-matrix.outputs.matrix }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2
      - name: "Set native test matrix"
        id: set-native-test-matrix
        run: |
          ./gradlew tasks --no-daemon --all
